package aed.ui;

import aed.dao.ClienteJpaController;
import aed.dao.exceptions.NonexistentEntityException;
import aed.map.Cliente;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DOMINGO
 */
public class ClienteUI extends javax.swing.JFrame {

    DefaultTableModel modelo;
    Cliente cliente = new Cliente();
    Cliente clienteAct = new Cliente();
    ClienteJpaController clienteJpa = new ClienteJpaController();

    /**
     * Creates new form Cliente
     */
    public ClienteUI() {
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Id Cliente");
        modelo.addColumn("DNI");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido 1º");
        modelo.addColumn("Apellido 2º");
        modelo.addColumn("Tipo de Vía");
        modelo.addColumn("Nombre de Vía");
        modelo.addColumn("Número de Vía");
        modelo.addColumn("Teléfono");
        this.jTabla.setModel(modelo);
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMercedes = new javax.swing.JPanel();
        lblMercedes = new javax.swing.JLabel();
        jpClientes = new javax.swing.JPanel();
        lblIdCliente = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApell1 = new javax.swing.JLabel();
        lblApell2 = new javax.swing.JLabel();
        lblTipoVia = new javax.swing.JLabel();
        lblNomVia = new javax.swing.JLabel();
        lblNumVia = new javax.swing.JLabel();
        lblTelf = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        jpDatos = new javax.swing.JPanel();
        txtIdCliente = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApell1 = new javax.swing.JTextField();
        txtApell2 = new javax.swing.JTextField();
        txtTipoVia = new javax.swing.JTextField();
        txtNomVia = new javax.swing.JTextField();
        txtNumVia = new javax.swing.JTextField();
        txtTelf = new javax.swing.JTextField();
        lblDatos = new javax.swing.JLabel();
        jpBotones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jpTabla = new javax.swing.JPanel();
        jspTabla = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes Concesionario");
        setResizable(false);

        lblMercedes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMercedes.setIcon(new javax.swing.ImageIcon("C:\\Users\\DOMINGO\\Documents\\NetBeansProjects\\proyectORM\\src\\main\\java\\aed\\ui\\img\\logo_lettersx56.png")); // NOI18N
        lblMercedes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpMercedesLayout = new javax.swing.GroupLayout(jpMercedes);
        jpMercedes.setLayout(jpMercedesLayout);
        jpMercedesLayout.setHorizontalGroup(
            jpMercedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMercedesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblMercedes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMercedesLayout.setVerticalGroup(
            jpMercedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMercedesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblMercedes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblIdCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIdCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdCliente.setText("Id Cliente");
        lblIdCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblDNI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDNI.setText("DNI");
        lblDNI.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre");
        lblNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblApell1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblApell1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApell1.setText("Apellido 1º");
        lblApell1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblApell2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblApell2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApell2.setText("Apellido 2º");
        lblApell2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblTipoVia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTipoVia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoVia.setText("Tipo de Vía");
        lblTipoVia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblNomVia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNomVia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomVia.setText("Nombre de Vía");
        lblNomVia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblNumVia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNumVia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumVia.setText("Número de Vía");
        lblNumVia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblTelf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTelf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTelf.setText("Teléfono");
        lblTelf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        javax.swing.GroupLayout jpClientesLayout = new javax.swing.GroupLayout(jpClientes);
        jpClientes.setLayout(jpClientesLayout);
        jpClientesLayout.setHorizontalGroup(
            jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDNI, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblApell1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblApell2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTipoVia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNomVia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNumVia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTelf, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpClientesLayout.setVerticalGroup(
            jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblIdCliente))
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lblNombre))
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblDNI))
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(lblApell1))
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(lblNumVia))
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(lblTelf))
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(lblTipoVia))
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(lblNomVia))
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(lblApell2))
            .addComponent(lblClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        txtIdCliente.setEnabled(false);

        lblDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        javax.swing.GroupLayout jpDatosLayout = new javax.swing.GroupLayout(jpDatos);
        jpDatos.setLayout(jpDatosLayout);
        jpDatosLayout.setHorizontalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApell1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApell2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoVia, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomVia, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumVia, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelf, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jpDatosLayout.setVerticalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtApell1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtApell2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtTipoVia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtNomVia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtNumVia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtTelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotonesLayout = new javax.swing.GroupLayout(jpBotones);
        jpBotones.setLayout(jpBotonesLayout);
        jpBotonesLayout.setHorizontalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotonesLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBotonesLayout.setVerticalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotonesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaMouseClicked(evt);
            }
        });
        jspTabla.setViewportView(jTabla);

        javax.swing.GroupLayout jpTablaLayout = new javax.swing.GroupLayout(jpTabla);
        jpTabla.setLayout(jpTablaLayout);
        jpTablaLayout.setHorizontalGroup(
            jpTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTablaLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jspTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))
        );
        jpTablaLayout.setVerticalGroup(
            jpTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTablaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jspTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpBotones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpMercedes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(jpTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMercedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
        JOptionPane.showMessageDialog(null, "Limpieza de Campos, Exitosa!!!");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarCliente();
        DefaultTableModel modelo = (DefaultTableModel) jTabla.getModel();
        modelo.setRowCount(0);
        llenarTabla();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaMouseClicked
        clickTabla();
    }//GEN-LAST:event_jTablaMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarCliente();
        DefaultTableModel modelo = (DefaultTableModel) jTabla.getModel();
        modelo.setRowCount(0);
        llenarTabla();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        actualizarCliente();
        DefaultTableModel modelo = (DefaultTableModel) jTabla.getModel();
        modelo.setRowCount(0);
        llenarTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void limpiarCampos() {
        txtIdCliente.setText("");
        txtDni.setText("");
        txtNombre.setText("");
        txtApell1.setText("");
        txtApell2.setText("");
        txtTipoVia.setText("");
        txtNomVia.setText("");
        txtNumVia.setText("");
        txtTelf.setText("");
    }

    private void llenarTabla() {
        try {
            Object A[] = null;
            List<Cliente> ListaClientes;
            ListaClientes = clienteJpa.findClienteEntities();
            for (int i = 0; i < ListaClientes.size(); i++) {
                modelo.addRow(A);
                modelo.setValueAt(ListaClientes.get(i).getIdCliente(), i, 0);
                modelo.setValueAt(ListaClientes.get(i).getDni(), i, 1);
                modelo.setValueAt(ListaClientes.get(i).getNombre(), i, 2);
                modelo.setValueAt(ListaClientes.get(i).getApellido1(), i, 3);
                modelo.setValueAt(ListaClientes.get(i).getApellido2(), i, 4);
                modelo.setValueAt(ListaClientes.get(i).getTipoVia(), i, 5);
                modelo.setValueAt(ListaClientes.get(i).getNombreVia(), i, 6);
                modelo.setValueAt(ListaClientes.get(i).getNumeroVia(), i, 7);
                modelo.setValueAt(ListaClientes.get(i).getTelefono(), i, 8);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error llenando Tabla, err: " + e.toString());
        }
    }

    private void guardarCliente() {
        cliente.setDni(txtDni.getText());
        cliente.setNombre(txtNombre.getText());
        cliente.setApellido1(txtApell1.getText());
        cliente.setApellido2(txtApell2.getText());
        cliente.setTipoVia(txtTipoVia.getText());
        cliente.setNombreVia(txtNomVia.getText());
        cliente.setNumeroVia(txtNumVia.getText());
        cliente.setTelefono(txtTelf.getText());
        limpiarCampos();
        clienteJpa.create(cliente);
        JOptionPane.showMessageDialog(null, "Cliente Registrado con Exito!!!");
    }

    private void eliminarCliente() {
        Integer id = Integer.parseInt(txtIdCliente.getText());
        try {
            limpiarCampos();
            clienteJpa.destroy(id);
            JOptionPane.showMessageDialog(null, "Cliente Eliminado con Exito!!!");
        } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, "Error en la Eliminación del Cliente, err: " + ex.toString());
        }
    }

    private void actualizarCliente() {
        try {
            clienteAct.setIdCliente(Integer.parseInt(txtIdCliente.getText()));
            clienteAct.setDni(txtDni.getText());
            clienteAct.setNombre(txtNombre.getText());
            clienteAct.setApellido1(txtApell1.getText());
            clienteAct.setApellido2(txtApell2.getText());
            clienteAct.setTipoVia(txtTipoVia.getText());
            clienteAct.setNombreVia(txtNomVia.getText());
            clienteAct.setNumeroVia(txtNumVia.getText());
            clienteAct.setTelefono(txtTelf.getText());
            limpiarCampos();
            clienteJpa.edit(clienteAct);
            JOptionPane.showMessageDialog(null, "Cliente Actualizado con Exito!!!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error en la Actualización del Cliente, err: " + ex.toString());
        }
    }

    private void clickTabla() {
        Integer id = (Integer) jTabla.getValueAt(jTabla.getSelectedRow(), 0);
        String dni = (String) jTabla.getValueAt(jTabla.getSelectedRow(), 1);
        String nombre = (String) jTabla.getValueAt(jTabla.getSelectedRow(), 2);
        String apellido1 = (String) jTabla.getValueAt(jTabla.getSelectedRow(), 3);
        String apellido2 = (String) jTabla.getValueAt(jTabla.getSelectedRow(), 4);
        String tipovia = (String) jTabla.getValueAt(jTabla.getSelectedRow(), 5);
        String nombrevia = (String) jTabla.getValueAt(jTabla.getSelectedRow(), 6);
        String numerovia = (String) jTabla.getValueAt(jTabla.getSelectedRow(), 7);
        String telefono = (String) jTabla.getValueAt(jTabla.getSelectedRow(), 8);
        txtIdCliente.setText(Integer.toString(id));
        txtDni.setText(dni);
        txtNombre.setText(nombre);
        txtApell1.setText(apellido1);
        txtApell2.setText(apellido2);
        txtTipoVia.setText(tipovia);
        txtNomVia.setText(nombrevia);
        txtNumVia.setText(numerovia);
        txtTelf.setText(telefono);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JTable jTabla;
    private javax.swing.JPanel jpBotones;
    private javax.swing.JPanel jpClientes;
    private javax.swing.JPanel jpDatos;
    private javax.swing.JPanel jpMercedes;
    private javax.swing.JPanel jpTabla;
    private javax.swing.JScrollPane jspTabla;
    private javax.swing.JLabel lblApell1;
    private javax.swing.JLabel lblApell2;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblDatos;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblMercedes;
    private javax.swing.JLabel lblNomVia;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumVia;
    private javax.swing.JLabel lblTelf;
    private javax.swing.JLabel lblTipoVia;
    private javax.swing.JTextField txtApell1;
    private javax.swing.JTextField txtApell2;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtNomVia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumVia;
    private javax.swing.JTextField txtTelf;
    private javax.swing.JTextField txtTipoVia;
    // End of variables declaration//GEN-END:variables
}
