package aed.ui;

import aed.dao.CocheJpaController;
import aed.map.Cliente;
import aed.map.Coche;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DOMINGO
 */
public class CocheUI extends javax.swing.JFrame {

    DefaultTableModel modelo;
    CocheJpaController cocheJpa = new CocheJpaController();
    Coche coche = new Coche();
    Coche cocheAct = new Coche();

    /**
     * Creates new form Cliente
     */
    public CocheUI() {
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Id Coche");
        modelo.addColumn("Id Cliente");
        modelo.addColumn("Marca");
        modelo.addColumn("Modelo");
        modelo.addColumn("Color");
        modelo.addColumn("Precio");
        modelo.addColumn("Matrícula");
        this.jTabla.setModel(modelo);
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        concesionarioUPEntityManager0 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("concesionarioUP").createEntityManager();
        clienteQuery = java.beans.Beans.isDesignTime() ? null : concesionarioUPEntityManager0.createQuery("SELECT c FROM Cliente c");
        clienteList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : clienteQuery.getResultList();
        jpMercedes = new javax.swing.JPanel();
        lblMercedes = new javax.swing.JLabel();
        jpCoches = new javax.swing.JPanel();
        lblIdCoche = new javax.swing.JLabel();
        lblIdCliente = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        lblCoches = new javax.swing.JLabel();
        jpDatos = new javax.swing.JPanel();
        txtIdCoche = new javax.swing.JTextField();
        jComboIdCliente = new javax.swing.JComboBox<>();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        lblDatos = new javax.swing.JLabel();
        jpBotones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jpTabla = new javax.swing.JPanel();
        jspTabla = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Coches Concesionario");
        setResizable(false);

        lblMercedes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMercedes.setIcon(new javax.swing.ImageIcon("C:\\Users\\DOMINGO\\Documents\\NetBeansProjects\\proyectORM\\src\\main\\java\\aed\\ui\\img\\logo_lettersx56.png")); // NOI18N
        lblMercedes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpMercedesLayout = new javax.swing.GroupLayout(jpMercedes);
        jpMercedes.setLayout(jpMercedesLayout);
        jpMercedesLayout.setHorizontalGroup(
            jpMercedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMercedesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblMercedes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMercedesLayout.setVerticalGroup(
            jpMercedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMercedesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblMercedes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblIdCoche.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIdCoche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdCoche.setText("Id Coche");
        lblIdCoche.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblIdCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIdCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdCliente.setText("Id Cliente");
        lblIdCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblMarca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMarca.setText("Marca");
        lblMarca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblModelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblModelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModelo.setText("Modelo");
        lblModelo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblColor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblColor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColor.setText("Color");
        lblColor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblPrecio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecio.setText("Precio");
        lblPrecio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblMatricula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMatricula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMatricula.setText("Matrícula");
        lblMatricula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblCoches.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Coches", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        javax.swing.GroupLayout jpCochesLayout = new javax.swing.GroupLayout(jpCoches);
        jpCoches.setLayout(jpCochesLayout);
        jpCochesLayout.setHorizontalGroup(
            jpCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCochesLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jpCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdCoche, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIdCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMarca, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblModelo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblColor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPrecio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMatricula, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(jpCochesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblCoches, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpCochesLayout.setVerticalGroup(
            jpCochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCochesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblIdCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblCoches, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        txtIdCoche.setEnabled(false);

        jComboIdCliente.setMinimumSize(new java.awt.Dimension(6, 20));
        jComboIdCliente.setPreferredSize(new java.awt.Dimension(6, 20));

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, clienteList, jComboIdCliente);
        bindingGroup.addBinding(jComboBoxBinding);

        lblDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        javax.swing.GroupLayout jpDatosLayout = new javax.swing.GroupLayout(jpDatos);
        jpDatos.setLayout(jpDatosLayout);
        jpDatosLayout.setHorizontalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(txtIdCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jComboIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(lblDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpDatosLayout.setVerticalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtIdCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jComboIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotonesLayout = new javax.swing.GroupLayout(jpBotones);
        jpBotones.setLayout(jpBotonesLayout);
        jpBotonesLayout.setHorizontalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotonesLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBotonesLayout.setVerticalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotonesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaMouseClicked(evt);
            }
        });
        jspTabla.setViewportView(jTabla);

        javax.swing.GroupLayout jpTablaLayout = new javax.swing.GroupLayout(jpTabla);
        jpTabla.setLayout(jpTablaLayout);
        jpTablaLayout.setHorizontalGroup(
            jpTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTablaLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jspTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))
        );
        jpTablaLayout.setVerticalGroup(
            jpTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTablaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jspTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpBotones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpMercedes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpCoches, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(jpTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMercedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpCoches, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
        JOptionPane.showMessageDialog(null, "Limpieza de Campos, Exitosa!!!");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarCoche();
        DefaultTableModel modelo = (DefaultTableModel) jTabla.getModel();
        modelo.setRowCount(0);
        llenarTabla();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaMouseClicked
        clickTabla();
        DefaultTableModel modelo = (DefaultTableModel) jTabla.getModel();
        modelo.setRowCount(0);
        llenarTabla();
    }//GEN-LAST:event_jTablaMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        actualizarCoche();
        DefaultTableModel modelo = (DefaultTableModel) jTabla.getModel();
        modelo.setRowCount(0);
        llenarTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void limpiarCampos() {
        txtIdCoche.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtColor.setText("");
        txtPrecio.setText("");
        txtMatricula.setText("");
    }

    private void llenarTabla() {
        try {
            Object A[] = null;
            List<Coche> ListaCoches;
            ListaCoches = cocheJpa.findCocheEntities();
            for (int i = 0; i < ListaCoches.size(); i++) {
                modelo.addRow(A);
                modelo.setValueAt(ListaCoches.get(i).getIdCoche(), i, 0);
                modelo.setValueAt(ListaCoches.get(i).getIdCliente(), i, 1);
                modelo.setValueAt(ListaCoches.get(i).getMarca(), i, 2);
                modelo.setValueAt(ListaCoches.get(i).getModelo(), i, 3);
                modelo.setValueAt(ListaCoches.get(i).getColor(), i, 4);
                modelo.setValueAt(ListaCoches.get(i).getPrecio(), i, 5);
                modelo.setValueAt(ListaCoches.get(i).getMatricula(), i, 6);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    private void guardarCoche() {
        coche.setIdCliente((Cliente) jComboIdCliente.getSelectedItem());
        coche.setMarca(txtMarca.getText());
        coche.setModelo(txtModelo.getText());
        coche.setColor(txtColor.getText());
        coche.setPrecio(Float.valueOf(txtPrecio.getText()));
        coche.setMatricula(txtMatricula.getText());
        limpiarCampos();
        cocheJpa.create(coche);
        JOptionPane.showMessageDialog(null, "Coche Registrado con Exito!!!");
        llenarTabla();
    }

    private void clickTabla() {
        Integer id = (Integer) jTabla.getValueAt(jTabla.getSelectedRow(), 0);
        Cliente id2 = (Cliente) jTabla.getValueAt(jTabla.getSelectedRow(), 1);
        String marca = (String) jTabla.getValueAt(jTabla.getSelectedRow(), 2);
        String modelcoche = (String) jTabla.getValueAt(jTabla.getSelectedRow(), 3);
        String color = (String) jTabla.getValueAt(jTabla.getSelectedRow(), 4);
        Float precio = (Float) jTabla.getValueAt(jTabla.getSelectedRow(), 5);
        String matricula = (String) jTabla.getValueAt(jTabla.getSelectedRow(), 6);
        txtIdCoche.setText(Integer.toString(id));
        jComboIdCliente.setSelectedItem(id2);
        txtMarca.setText(marca);
        txtModelo.setText(modelcoche);
        txtColor.setText(color);
        txtPrecio.setText(Float.toString(precio));
        txtMatricula.setText(matricula);
    }

    private void actualizarCoche() {
        cocheAct.setIdCoche(Integer.parseInt(txtIdCoche.getText()));
        cocheAct.setIdCliente((Cliente) jComboIdCliente.getSelectedItem());
        cocheAct.setMarca(txtMarca.getText());
        cocheAct.setModelo(txtModelo.getText());
        cocheAct.setColor(txtColor.getText());
        cocheAct.setPrecio(Float.valueOf(txtPrecio.getText()));
        cocheAct.setMatricula(txtMatricula.getText());
        try {
            limpiarCampos();
            cocheJpa.edit(cocheAct);
            JOptionPane.showMessageDialog(null, "Actualización Exitosa!!!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error en la Actualización del Cliente, err: " + ex.toString());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private java.util.List<aed.map.Cliente> clienteList;
    private javax.persistence.Query clienteQuery;
    private javax.persistence.EntityManager concesionarioUPEntityManager0;
    private javax.swing.JComboBox<String> jComboIdCliente;
    private javax.swing.JTable jTabla;
    private javax.swing.JPanel jpBotones;
    private javax.swing.JPanel jpCoches;
    private javax.swing.JPanel jpDatos;
    private javax.swing.JPanel jpMercedes;
    private javax.swing.JPanel jpTabla;
    private javax.swing.JScrollPane jspTabla;
    private javax.swing.JLabel lblCoches;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblDatos;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblIdCoche;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblMercedes;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtIdCoche;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPrecio;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
