package aed.ui;

/**
 *
 * @author DOMINGO
 */
public class InitUI extends javax.swing.JFrame {

    /**
     * Creates new form Init
     */
    public InitUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMercedes = new javax.swing.JPanel();
        lblMercedes = new javax.swing.JLabel();
        jpCoche = new javax.swing.JPanel();
        btnCoche = new javax.swing.JButton();
        jpCliente = new javax.swing.JPanel();
        btnCliente = new javax.swing.JButton();
        jpRevision = new javax.swing.JPanel();
        btnRevision = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Concesionario Mercedes Benz");
        setResizable(false);

        lblMercedes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMercedes.setIcon(new javax.swing.ImageIcon("C:\\Users\\DOMINGO\\Documents\\NetBeansProjects\\proyectORM\\src\\main\\java\\aed\\ui\\img\\logo_letters128.png")); // NOI18N
        lblMercedes.setToolTipText("Concesionario Oficial Mercedes-Benz");

        javax.swing.GroupLayout jpMercedesLayout = new javax.swing.GroupLayout(jpMercedes);
        jpMercedes.setLayout(jpMercedesLayout);
        jpMercedesLayout.setHorizontalGroup(
            jpMercedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMercedes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpMercedesLayout.setVerticalGroup(
            jpMercedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMercedesLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(lblMercedes))
        );

        btnCoche.setIcon(new javax.swing.ImageIcon("C:\\Users\\DOMINGO\\Documents\\NetBeansProjects\\proyectORM\\src\\main\\java\\aed\\ui\\img\\carx128x128.png")); // NOI18N
        btnCoche.setToolTipText("Registro de Coches");
        btnCoche.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCoche.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCocheLayout = new javax.swing.GroupLayout(jpCoche);
        jpCoche.setLayout(jpCocheLayout);
        jpCocheLayout.setHorizontalGroup(
            jpCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCocheLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnCoche)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jpCocheLayout.setVerticalGroup(
            jpCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCocheLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnCoche)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\DOMINGO\\Documents\\NetBeansProjects\\proyectORM\\src\\main\\java\\aed\\ui\\img\\client2x128x128.png")); // NOI18N
        btnCliente.setToolTipText("Registro de Clientes");
        btnCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpClienteLayout = new javax.swing.GroupLayout(jpCliente);
        jpCliente.setLayout(jpClienteLayout);
        jpClienteLayout.setHorizontalGroup(
            jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClienteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnCliente)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jpClienteLayout.setVerticalGroup(
            jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClienteLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnCliente)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jpRevision.setPreferredSize(new java.awt.Dimension(169, 155));

        btnRevision.setIcon(new javax.swing.ImageIcon("C:\\Users\\DOMINGO\\Documents\\NetBeansProjects\\proyectORM\\src\\main\\java\\aed\\ui\\img\\keyx128x128.png")); // NOI18N
        btnRevision.setToolTipText("Registro de Revisiones");
        btnRevision.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRevision.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRevision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevisionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpRevisionLayout = new javax.swing.GroupLayout(jpRevision);
        jpRevision.setLayout(jpRevisionLayout);
        jpRevisionLayout.setHorizontalGroup(
            jpRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRevisionLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnRevision, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jpRevisionLayout.setVerticalGroup(
            jpRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRevisionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnRevision)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMercedes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpRevision, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMercedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpCoche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpRevision, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocheActionPerformed
        CocheUI cocheui = new CocheUI();
        cocheui.setVisible(true);
        cocheui.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCocheActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        ClienteUI clienteui = new ClienteUI();
        clienteui.setVisible(true);
        clienteui.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnRevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevisionActionPerformed
        RevisionUI revisionui = new RevisionUI();
        revisionui.setVisible(true);
        revisionui.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRevisionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnCoche;
    private javax.swing.JButton btnRevision;
    private javax.swing.JPanel jpCliente;
    private javax.swing.JPanel jpCoche;
    private javax.swing.JPanel jpMercedes;
    private javax.swing.JPanel jpRevision;
    private javax.swing.JLabel lblMercedes;
    // End of variables declaration//GEN-END:variables
}
